on: [push]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    sast:
      runs-on: ubuntu-latest
      name: Run unit tests and SAST scan on the source code.
    slscan:
      runs-on: ubuntu-latest
      needs: depchecktest
    build_and_push:
      name: Build & Push to DockerHub 
      needs: slscan
      runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Login to DockerHub.
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 
      - name: Build with Maven
        run: mvn clean install
      - name: Docker Build and Push to DockerHub
        uses: docker/build-push-action@v5 
        with:
          context: .
          push: true
          tags: shichoc/devsecopsdiy:1.0
      - uses: ShiftLeftSecurity/scan-action@master 
        with:
          type: "credscan,java,depscan"
      - uses: actions/upload-artifact@master
        with:
          name: SLSCAN reports
          path: ${{github.workspace}}/reports
      - name: Build with Maven cloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=devsecopsdiy_test -Dsonar.organization=devsecopsdiy
              -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        continue-on-error: true
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
